INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_BITTOBYTE bitTobyte)

FIND_PATH(
    BITTOBYTE_INCLUDE_DIRS
    NAMES bitTobyte/api.h
    HINTS $ENV{BITTOBYTE_DIR}/include
        ${PC_BITTOBYTE_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    BITTOBYTE_LIBRARIES
    NAMES gnuradio-bitTobyte
    HINTS $ENV{BITTOBYTE_DIR}/lib
        ${PC_BITTOBYTE_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(BITTOBYTE DEFAULT_MSG BITTOBYTE_LIBRARIES BITTOBYTE_INCLUDE_DIRS)
MARK_AS_ADVANCED(BITTOBYTE_LIBRARIES BITTOBYTE_INCLUDE_DIRS)

